In [1]:
import numpy as np

# DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array ([[1, 2.0, 3.3],
                [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
                [13,14, 15],
                [16, 17, 18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
#Create a Dataframe from NumPy array
import pandas as pd

In [18]:
df = pd.DataFrame(a2)

In [19]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating NumPy Arrays

In [21]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [22]:
sample_array.dtype

dtype('int64')

In [23]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype


dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [28]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
range_array = np.arange(0,10, 2)
range_array

array([0, 2, 4, 6, 8])

In [33]:
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[0, 1, 2, 2, 7],
       [6, 6, 4, 1, 3],
       [6, 7, 7, 4, 0]])

In [34]:
random_array.size

15

In [35]:
random_array.shape

(3, 5)

In [43]:
random_array2 = np.random.random(size=(5,3))
random_array2

array([[0.52429072, 0.55093119, 0.48371811],
       [0.72108973, 0.29641829, 0.41704005],
       [0.23288017, 0.42231532, 0.16180142],
       [0.83015468, 0.78960138, 0.4254788 ],
       [0.37752351, 0.18424092, 0.30493892]])

In [42]:
random_array3 = np.random.rand(5,3)

In [44]:
random_array3

array([[0.78050272, 0.96582538, 0.21110603],
       [0.54124908, 0.40788629, 0.08406534],
       [0.85785804, 0.07391067, 0.96193196],
       [0.70788341, 0.14552188, 0.30589947],
       [0.44544141, 0.6515652 , 0.65422441]])

# 2. Pseudo-random numbers
# np.random.seed()

In [50]:
random_array_4 = np.random .randint(10, size=(5,3))
random_array_4

array([[6, 2, 4],
       [4, 3, 2],
       [0, 3, 7],
       [2, 6, 6],
       [3, 1, 0]])

In [48]:
random_array_4.shape

(5, 3)

In [51]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))

In [53]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [62]:
np.random.seed(seed=1)
random_array_5 = np.random.random((5,3))
random_array_5


array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01],
       [5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02]])

## 3. Viewing Arrays and matrices

In [63]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a1


array([1, 2, 3])

In [65]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [66]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [67]:
a1[0]

1

In [69]:
 a2[0]

array([1. , 2. , 3.3])

In [70]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
a2[1]

array([4. , 5. , 6.5])

In [73]:
a3[:2,:2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [74]:
a4 = np.random.randint( 10, size = (2,3,4,5))
a4

array([[[[2, 4, 7, 7, 9],
         [1, 7, 0, 6, 9],
         [9, 7, 6, 9, 1],
         [0, 1, 8, 8, 3]],

        [[9, 8, 7, 3, 6],
         [5, 1, 9, 3, 4],
         [8, 1, 4, 0, 3],
         [9, 2, 0, 4, 9]],

        [[2, 7, 7, 9, 8],
         [6, 9, 3, 7, 7],
         [4, 5, 9, 3, 6],
         [8, 0, 2, 7, 7]]],


       [[[9, 7, 3, 0, 8],
         [7, 7, 1, 1, 3],
         [0, 8, 6, 4, 5],
         [6, 2, 5, 7, 8]],

        [[4, 4, 7, 7, 4],
         [9, 0, 2, 0, 7],
         [1, 7, 9, 8, 4],
         [0, 1, 9, 8, 2]],

        [[3, 1, 2, 7, 2],
         [6, 0, 9, 2, 6],
         [6, 2, 7, 7, 0],
         [6, 5, 1, 4, 6]]]])

In [75]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [77]:
a4[:, :, :, :1]

array([[[[2],
         [1],
         [9],
         [0]],

        [[9],
         [5],
         [8],
         [9]],

        [[2],
         [6],
         [4],
         [8]]],


       [[[9],
         [7],
         [0],
         [6]],

        [[4],
         [9],
         [1],
         [0]],

        [[3],
         [6],
         [6],
         [6]]]])

## 4. Manipulating and comparing arrays

Arithmatic

In [78]:
a1

array([1, 2, 3])

In [80]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [81]:
a1+ones

array([2., 3., 4.])

In [82]:
a1-ones

array([0., 1., 2.])

In [83]:
a1 * ones

array([1., 2., 3.])

In [84]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [85]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [86]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [87]:
a1/ones

array([1., 2., 3.])

In [88]:
#floor division removes the decimals
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [90]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [91]:
np.add(a1, ones)

array([2., 3., 4.])

In [92]:
a1 % 2

array([1, 0, 1])

### Aggregation

Aggregation  = performing the same operation on a number of things

In [94]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [95]:
sum(listy_list)

6

In [96]:
np.sum(listy_list)

6

### Use Pythons's methods on Python datatypes and use NumPy methods on NumPy arrays

In [97]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [98]:
massive_array[:10]

array([0.5270581 , 0.8859421 , 0.35726976, 0.90853515, 0.62336012,
       0.01582124, 0.92943723, 0.69089692, 0.99732285, 0.17234051])

In [100]:
%timeit sum(massive_array) #Python
%timeit np.sum(massive_array) #NumPy

11 ms ± 194 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
73.2 µs ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [101]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [103]:
np.mean(a2)

3.6333333333333333

In [104]:
np.max(a2)

6.5

In [105]:
np.min(a2)

1.0

In [109]:
#Standard deviation = a measure of how spread out a group of number are from the mean
np.std(a2)

1.8226964152656422

In [108]:
# Variance = measure of the average degree to which each number is different to the mean
# Higer variance = higher range
# lower variance = lower range
np.var(a2)

3.3222222222222224

In [110]:
#Standard deviation = sqareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422

In [111]:
#Demo of STD and VAR
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2,4,6,8,10])

In [112]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [113]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)